version: '3.8'

services:
  todaypickup-api-client:
    build: .
    ports:
      - "8000:8000"
    environment:
      - TODAYPICKUP_BASE_URL=https://admin.todaypickup.com
      - TODAYPICKUP_API_PREFIX=/api
      - LOG_LEVEL=INFO
      - HTTP_TIMEOUT=30
      - HTTP_RETRIES=3
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s